title: Deep Learning Camp Jeju
description: Enjoy, Share, Grow
github: [metadata]
google_analytics: UA-112439062-1
baseurl: ''
repository: TensorFlowKR/dlcampjeju

theme: jekyll-theme-cayman
plugins:
  - jekyll-mentions
  - jekyll-minifier
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - README.md
